# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20181113_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
    ]
